In [20]:
#normal equation

import numpy as np

# Example dataset
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])  # Feature matrix
print("X:", X)

y = np.dot(X, np.array([1, 2])) + 3  # Target vector
print("Y", y)

# Add a column of ones to X to account for the intercept term
X = np.hstack([np.ones((X.shape[0], 1)), X])
print("X:", X)

# Calculate beta using the normal equation
beta = np.linalg.inv(X.T @ X) @ X.T @ y
print("Estimated coefficients:", beta)

X: [[1 1]
 [1 2]
 [2 2]
 [2 3]]
Y [ 6  8  9 11]
X: [[1. 1. 1.]
 [1. 1. 2.]
 [1. 2. 2.]
 [1. 2. 3.]]
Estimated coefficients: [3. 1. 2.]


In [17]:
#sparse matrix for memory optimisation

from scipy.sparse import csr_matrix

# Create a sparse matrix
dense_matrix = np.array([[0, 0, 3], [4, 0, 0], [0, 2, 0]])
sparse_matrix = csr_matrix(dense_matrix)

print(sparse_matrix)

  (0, 2)	3
  (1, 0)	4
  (2, 1)	2


In [18]:
#heaps

import heapq

# Example graph (as an adjacency list)
graph = {
    'A': [('B', 1), ('C', 4)],
    'B': [('A', 1), ('C', 2), ('D', 5)],
    'C': [('A', 4), ('B', 2), ('D', 1)],
    'D': [('B', 5), ('C', 1)]
}

# A* search function
def a_star(graph, start, goal, h):
    # Priority queue, initialized with the start node
    pq = [(0 + h(start), 0, start, [])]  # (f = g + h, g, node, path)
    heapq.heapify(pq)
    
    while pq:
        (f, g, current, path) = heapq.heappop(pq)
        
        # Path to the current node
        path = path + [current]
        
        if current == goal:
            return path, f  # Return the found path and its total cost
        
        for (neighbor, cost) in graph[current]:
            heapq.heappush(pq, (g + cost + h(neighbor), g + cost, neighbor, path))
    
    return None  # If no path is found

# Heuristic function (for simplicity, using zero heuristic as an example)
def h(node):
    return 0

# Find path from A to D
path, cost = a_star(graph, 'A', 'D', h)
print("Path:", path, "Cost:", cost)

Path: ['A', 'B', 'C', 'D'] Cost: 4


In [21]:
#K-means++

import numpy as np

def initialize_centroids(X, k):
    centroids = []
    centroids.append(X[np.random.randint(X.shape[0])])
    
    for _ in range(1, k):
        distances = np.array([min([np.linalg.norm(x - c) for c in centroids]) for x in X])
        heap = [(dist, i) for i, dist in enumerate(distances)]
        heapq.heapify(heap)
        
        # Weighted random selection of the next centroid
        total_dist = sum(distances)
        r = np.random.uniform(0, total_dist)
        cumulative_dist = 0
        
        for dist, i in heap:
            cumulative_dist += dist
            if cumulative_dist >= r:
                centroids.append(X[i])
                break
    
    return np.array(centroids)

# Example dataset
X = np.array([[1, 2], [1, 4], [3, 2], [5, 6], [7, 8], [9, 10]])
centroids = initialize_centroids(X, 2)
print("Initial centroids:\n", centroids)

Initial centroids:
 [[ 9 10]
 [ 5  6]]


In [22]:
#Hash Tables

# Example dataset: user interactions with items
user_interactions = {
    'user1': ['item1', 'item2', 'item3'],
    'user2': ['item2', 'item4'],
    'user3': ['item1', 'item4', 'item5'],
}

# Hash table (dictionary in Python) to store interactions
hash_table = {}

# Insert interactions into the hash table
for user, items in user_interactions.items():
    hash_table[user] = items

# Efficient lookup of a user's interactions
user = 'user2'
print(f"Items interacted with by {user}: {hash_table[user]}")

Items interacted with by user2: ['item2', 'item4']


In [23]:
#LSH

import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.random_projection import SparseRandomProjection

# Example dataset: 2D points
points = np.random.rand(1000, 2)

# Using random projections to approximate nearest neighbors
lsh = SparseRandomProjection(n_components=2)
projected_points = lsh.fit_transform(points)

# Using NearestNeighbors for finding approximate neighbors
nbrs = NearestNeighbors(n_neighbors=3, algorithm='ball_tree').fit(projected_points)
distances, indices = nbrs.kneighbors(projected_points)

# Example: Finding nearest neighbors of a point
point_index = 0
print(f"Nearest neighbors of point {point_index}: {indices[point_index]}")

Nearest neighbors of point 0: [  0 181  53]


In [24]:
hash_table = [[] for _ in range(10)]

def hash_function(key):
    return key % 10

def insert(hash_table, key, value):
    index = hash_function(key)
    hash_table[index].append((key, value))

insert(hash_table, 15, 'value1')
insert(hash_table, 25, 'value2')
print(hash_table)

[[], [], [], [], [], [(15, 'value1'), (25, 'value2')], [], [], [], []]
